# This is a basic workflow that is manually triggered
# Это базовый рабочий процесс, который запускается вручную

name: Main workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
# Управляет выполнением действия. Рабочий процесс запускается при ручном запуске с использованием пользовательского интерфейса или API.
on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.
    # Вводимые данные, которые принимает рабочий процесс.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        # В пользовательском интерфейсе вместо "имени" будет отображаться понятное описание
        description: 'Зачем запустил'
        # Default value if no value is explicitly provided
        # Значение по умолчанию, если явно не указано никакое значение
        default: 'просто тестирую'
        # Input has to be provided for the workflow to run
        # Для запуска рабочего процесса должны быть предоставлены входные данные
        required: true
        # The data type of the input
        # Тип входных данных
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Запуск рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  send_message:
    runs-on: ubuntu-latest
#    needs: greet  deploy или другие шаги.
    steps:
      - name: Send message on manual workflow
        if: "${{ github.event.inputs.name != '' }}"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Репозиторий: ${{ github.repository }}
            Запустил ручками ${{ github.workflow }}, потому что - ${{ inputs.name }}"
      - name: Send message on push commit
        if: "${{ github.event.inputs.name == '' }}"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Деплой успешно выполнен!
            ${{ github.actor }} запушил комит - "${{ github.event.commits[0].message }}"
            Репозиторий: ${{ github.repository }}
            Посмотреть изменения:  https://github.com/${{ github.repository }}/commit/${{github.sha}}
